### ISSUE TITLE
Sync  Chart to clusterpedia-helm repo

### ISSUE THREAD

**Issue by lengrongfu** [clusterpedia-io/clusterpedia#389]
### What would you like to be added?

Sync  Chart to clusterpedia-helm repo

### Why is this needed?

Sync  Chart to clusterpedia-helm repo

**Comment by Iceber** [comment]
https://github.com/clusterpedia-io/clusterpedia-helm repo has been created

**Comment by Iceber** [comment]
Local charts are deprecated, but we will not close the page and delete charts/index.yaml so that existing users can continue to use them.

Now e2e tests still use local charts, which will be removed when we provide the kustomize deployment option.
We track the development of kustomize in a new issue.
